version: 2
general:
  branches:
    only:
     - cirlce-ci

jobs:
  sync:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            sudo apt-get -qq update
            sudo apt-get install -y git git-svn
      - run:
          name: Sync
          command: ./sync.sh

workflows:
  version: 2
  all:
    jobs:
      - sync
  scheduled:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - cirlce-ci
    jobs:
      - sync