version: 2
general:
  branches:
    only:
     - circle-ci

test:
  override:
    - echo "done"  

jobs:
  sync:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            sudo apt-get -qq update
            sudo apt-get install -y git git-svn
      - run:
          name: Sync
          command: ./sync.sh

workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - circle-ci
    jobs:
      - sync